### PR TITLE
Added library with Raspberry Pi V2 board

### PR DESCRIPTION
**Pull request by sharrington93**

### CODE REVIEW

**Comment by sharrington93** [comment]
@aaronbeekay can you check this to make sure I meet merging requirements?

**Comment by aaronbeekay** [comment]
@sharrington93 

* Device "RASPBERRYPIV2" needs:
  * a description
  * "PARTNO" attribute (this is manufacturer part number)
* Symbol:
  * It looks like you drew the component outline using a rectangle (rect) on the "Symbol" layer -- you should draw a box using lines instead -- should look like this 
image
  * Need ">NAME" and ">VALUE" text elements in symbol
  * Your symbol is too narrow -- the names of the pins inside the symbol overlap currently (see image above)
* Package:
  * The ">NAME" and ">VALUE" elements are pretty big, I would make those a lot smaller. For this particular component, you are allowed to place them outside the board outline (since they might get in the way of placing components later on)
  * Pins should be named "1", "2", "3", etc., not "P$1", "P$2", "P$3"
  * Why did you draw a rectangle around the pins on the bDocu layer? This might be a good place to put a rectangle on bKeepout
  * You have drawn a board outline on the bDocu layer -- this is a good idea but I might put it on the tDocu layer as well. 
  * You have a stray line on the "Dimension" layer above the PCB -- forgot to delete?
  * It is often helpful to label pin 1 (at least) of a header on the tPlace or bPlace layer - this will help with troubleshooting. It is also a convention to make the first pin of a 0.1" pin header like that square.
  * You should draw circles on the tDocu and tKeepout layers to represent the size of the mounting screw head

**Comment by sharrington93** [comment]
Questions:
* Difference between bDocu and tDocu? Do I need to make duplicates of things to put them on both?
* This is just the Raspberry Pi board outline, not the cape I plan on making. Does this change anything? 
* There's no PARTNO as far as I can tell. The best would be "rev2". Does that work?

**Comment by sharrington93** [comment]
I believe I fixed all the issues you brought up.

**Pull request merged**
