### PR TITLE
Added relative directories to OSH Park 2-layer job file.

### PR DESCRIPTION
**Pull request by cgreenbaum**
This modification puts CAM files into a directory named CAM within the project folder.

### CODE REVIEW

**Comment by cgreenbaum** [comment]
Added parts for the clicky boards

**Comment by sharrington93** [comment]
@cgreenbaum I'm in the process of manually merging. From looking at your commits, I have found the following components added by you:

TE -> Power Resistor
HASCO -> KLT Relay
TI -> DRV8860
Zettler -> AZ696 Relay

Am I missing anything?

**Comment by sharrington93** [comment]
@cgreenbaum two issues with the AZ696 Relay. You did not rename the pins from P$1, P$2 etc and did not give a component outline on TDocu layer.

Otherwise looks good.

**Comment by sharrington93** [comment]
Update: Looks like you don't use the Zettler library in the balancer relay circuit and it was replaced by the Hasco library essentially. If you don't care about this Zettler library, let me know and I will simply delete. Otherwise it's missing from the partsdb as well and will need added there.

**Comment by cgreenbaum** [comment]
Correct, I don't use the Zettler library. I will delete it and push the update.... Done.

**Pull request merged**
