### PR TITLE
Added parts for 18650 Busboards

### PR DESCRIPTION
**Pull request by Victorb101**
Added parts in BuckeyeCurrent.lbr and partsdb.txt

### CODE REVIEW

**Comment by aaronbeekay** [comment]
beep beep standards

* This seems to be a Keystone Electronics part - it needs to be in Keystone.lbr.
* Symbol needs name and value
* Component definition needs:
  * PARTNO attribute
  * Prefix
* Package needs:
  * Description
  * Name and value text

Also, you rewrote a lot of the lines in partsdb.txt. I know it's easy to do that by accident when you're editing partsdb with a spreadsheet editor -- can you see if there's some setting you can find that doesn't rewrite lines that way?

Alternatively, you can use a text editor like Notepad++ to edit the file and be sure that you aren't overwriting big chunks of it like that.

**Comment by Victorb101** [comment]
@aaronbeekay I dont know what you mean by I rewrote lines in partsdb.txt.  I added like 5 lines to my file, but nothing is repeated.  You'll have to show me what you mean.

I will fix the other stuff soon.

**Comment by aaronbeekay** [comment]
@Victorb101 - check out the diff: https://github.com/BuckeyeCurrent/Component-libraries/pull/82/files

It looks like your spreadsheet program is stripping the quotes from quoted cells, and converting numerical cells by stripping the leading zero ("0603" -> "603"). Sometimes you can fuck with the import options to make this behave better.

**Comment by Victorb101** [comment]
@aaronbeekay Will you check this pull request?  Now has libraries up to date for Noisemaker MCN Backpack.

**Comment by aaronbeekay** [comment]
Most of the stuff I wrote above is still outstanding (18650 part in wrong library, schematic standards issues).

There is a merge conflict with your TI.lbr and Fairchild Semiconductor.lbr. I suspect your Fairchild conflict is because you edited it and then sent it to Kim for her to submit (I modified it before merging it). Did you make any other changes in Fairchild Semiconductor.lbr? If not, I will use my fixed version from a71ae87d3f69600f671f39ef7fe3c3fc96512c65.

Your TI merge conflict looks like it's because you don't have Kim's changes in 843ae3a28aa6bda640f732c709c5a3231837af23. If you make a copy of your current TI.lbr (with the DAC7821), then download the latest version from Component-libraries and copy the DAC7821 into it, you should be good to go.

**Comment by aaronbeekay** [comment]
Unfortunately resolving merge conflicts just sucks this year. I'm actually a bit surprised we haven't run into this more often. Hopefully we will be able to make upgrades soon.

**Comment by Victorb101** [comment]
@aaronbeekay Ok, I fixed the errors mentioned.  Just don't pull the previously committed Buckeye Current.lbr.  Only TI.lbr and Keystone.lbr have desired changes.

**Comment by aaronbeekay** [comment]
OK, merged. I will be a little bit annoying and tell you that these merges will go a lot easier if you make more regular PRs.

**Pull request merged**
