### PR TITLE
Created JSM-12V-5 in Panasonic library

### PR DESCRIPTION
**Pull request by kimconcillado**

### CODE REVIEW

**Comment by aaronbeekay** [comment]
@kimconcillado - your commit note says,

> there has been a lot of edits to the device noted in the description. Should this be updated by deletion of the BMC device?

I think you're asking if you should delete the "LMP8601" device that was in "BMC components.lbr" -- yes, I think that's a good idea.

As a side note, commit notes aren't a very good place for questions like those, because nobody is notified of them, and there's no convenient way to have a conversation. Adding a comment to the pull request with an @mention works great.

**Comment by aaronbeekay** [comment]
#### Panasonic.lbr
* `JSM1-12V-5` device needs PARTNO attribute
* `JSM1-12V-5` device needs description
* **Important:** pin numbering on `JSM1-12V-5` package is mirrored. Somewhat confusingly, relay datasheets are often drawn from the *bottom* of the device – this means that the pins will be mirrored when you draw the component package (which is viewed from the top of the board). The correct pin numberings are: 

> relay_pin_numbering

* It is convenient if the component name/value is inside the package.

**Comment by aaronbeekay** [comment]
Oh, and -- you'll probably need an entry in partsdb.txt for that relay.

**Comment by kimconcillado** [comment]
@aaronbeekay check this above

**Comment by aaronbeekay** [comment]
Approved. A few minor edits:

* Had to merge changes in TI.lbr manually - @kimconcillado in the future, if you're able to fix issues in these PRs faster, it saves some trouble. This is an unfortunate side effect of the binary EAGLE library format we're currently working with.
* Shifted around the name and value in the SOIC8 footprint in TI.lbr
* Added a PARTNO attribute to the LMP8601 component in TI.lbr

@kimconcillado Please try to keep your commit notes more professional and informative than "hi" or "edited it again".

**Pull request merged**
